# Generated by Django 4.2.14 on 2024-08-18 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=1, upload_to='comment')),
                ('text', models.TextField(blank=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('count_likes', models.IntegerField(default=0)),
                ('count_comments', models.IntegerField(default=0)),
                ('likers', models.JSONField()),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Reacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=1, upload_to='comment')),
                ('text', models.TextField(blank=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('count_likes', models.IntegerField(default=0)),
                ('likers', models.JSONField()),
                ('Comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.comments')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='posts')),
                ('count_likes', models.IntegerField(default=0)),
                ('count_comments', models.IntegerField(default=0)),
                ('likers', models.JSONField()),
                ('creater', models.ForeignKey(blank=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.account')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.posts'),
        ),
    ]
