# Generated by Django 4.2.14 on 2024-08-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=0, max_length=50)),
                ('password', models.CharField(blank=0, max_length=50)),
                ('name', models.CharField(blank=0, max_length=50)),
                ('sex', models.CharField(blank=0, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('image', models.ImageField(default='profile/avatar-default.svg', upload_to='profile')),
                ('email', models.EmailField(blank=0, max_length=254)),
                ('date', models.DateField(blank=0)),
            ],
        ),
    ]
